# Generated by Django 5.0.3 on 2026-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=240)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaEstreno', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('imagenPortada', models.URLField(blank=True, null=True)),
                ('numeroEpisodios', models.IntegerField(default=1)),
                ('estado', models.CharField(max_length=50)),
                ('valoracionMedia', models.FloatField(default=0)),
                ('totalValoraciones', models.IntegerField(default=0)),
            ],
        ),
    ]
