# Generated by Django 5.0.3 on 2026-04-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLista', models.CharField(max_length=100)),
                ('fechaAgregado', models.DateField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listasUsuario', to='user.user')),
                ('series', models.ManyToManyField(blank=True, related_name='listasUsuario', to='serie.serie')),
            ],
        ),
    ]
