# Generated by Django 5.0.3 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('PENDIENTE', 'Pendiente'),
                            ('ACEPTADO', 'Aceptado'),
                            ('RECHAZADO', 'Rechazado'),
                        ],
                        default='PENDIENTE',
                        max_length=20,
                    ),
                ),
                (
                    'comentario',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='interaccion.comentario',
                    ),
                ),
                (
                    'usuario',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='user.user',
                    ),
                ),
            ],
        ),
    ]
