# Generated by Django 5.0.3 on 2026-05-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaccion', '0002_reportecomentario'),
        ('user', '0002_ensure_role_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLike', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interaccion.comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_likes', to='user.user')),
            ],
            options={
                'indexes': [models.Index(fields=['comentario', 'user'], name='interaccion_comenta_c3214a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='likecomentario',
            constraint=models.UniqueConstraint(fields=('comentario', 'user'), name='unique_like_comentario_user'),
        ),
    ]
