# Generated by Django 5.0.3 on 2026-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleId', models.CharField(max_length=255)),
                ('moduleName', models.CharField(max_length=255)),
            ],
        ),
    ]
