# Generated by Django 5.0.3 on 2026-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0Sub', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('apellidos', models.CharField(blank=True, default='', max_length=255)),
                ('fotoPerfil', models.CharField(blank=True, default='', max_length=255)),
                ('estadoCuenta', models.CharField(blank=True, default='Activa', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
            ],
        ),
    ]
