# Generated by Django 5.0.3 on 2026-04-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoLista', models.CharField(max_length=255)),
                ('fechaAgregado', models.DateField()),
                ('series', models.ManyToManyField(to='serie.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodiosVistos', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('ultimaActualizacion', models.DateField()),
                ('estado', models.CharField(max_length=255)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serie.serie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
