# Generated by Django 5.0.3 on 2026-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listausuario',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listausuario',
            name='fechaAgregado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
