# Generated by Django 5.0.3 on 2026-05-19 17:46

import django.db.models.deletion
from django.db import migrations, models


def populate_listaserie(apps, schema_editor):
    ListaUsuario = apps.get_model('listas', 'ListaUsuario')
    ListaSerie = apps.get_model('listas', 'ListaSerie')
    db_alias = schema_editor.connection.alias
    registros = []

    for lista in ListaUsuario.objects.using(db_alias).all():
        for serie_id in lista.series.values_list('id', flat=True):
            registros.append(ListaSerie(lista_id=lista.id, serie_id=serie_id))

    if registros:
        ListaSerie.objects.using(db_alias).bulk_create(registros, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAgregado', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesRegistros', to='listas.listausuario')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serie.serie')),
            ],
            options={
                'indexes': [models.Index(fields=['lista', '-fechaAgregado'], name='listas_list_lista_i_c73d52_idx')],
            },
        ),
        migrations.RunPython(populate_listaserie, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='listaserie',
            constraint=models.UniqueConstraint(fields=('lista', 'serie'), name='unique_lista_serie_registro'),
        ),
    ]
