# Generated by Django 5.0.3 on 2026-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_listausuario_descripcion_and_more'),
        ('serie', '0001_initial'),
        ('user', '0004_user_auth0sub_alter_user_apellidos_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progresoserie',
            constraint=models.UniqueConstraint(fields=('user', 'serie'), name='unique_user_serie_progress'),
        ),
    ]
