# Generated by Django 5.0.3 on 2026-05-19 13:10

import django.utils.timezone
from django.db import migrations, models


def normalize_friendship_rows(apps, schema_editor):
    Amistad = apps.get_model('social', 'Amistad')

    for amistad in Amistad.objects.all():
        normalized = {
            'pendiente': 'Pendiente',
            'pending': 'Pendiente',
            'aceptada': 'Aceptada',
            'accepted': 'Aceptada',
            'denegada': 'Denegada',
            'rechazada': 'Denegada',
            'denied': 'Denegada',
        }.get(f'{amistad.estado}'.strip().lower(), amistad.estado)

        amistad.estado = normalized

        if amistad.estado == 'Aceptada' and amistad.fechaAmistad is None:
            amistad.fechaAmistad = amistad.fechaRespuesta or amistad.fechaSolicitud

        amistad.save(update_fields=['estado', 'fechaAmistad'])


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('user', '0002_ensure_role_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistad',
            name='fechaAmistad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Denegada', 'Denegada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='fechaSolicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(normalize_friendship_rows, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='amistad',
            index=models.Index(fields=['user', 'user2'], name='social_amis_user_id_036849_idx'),
        ),
        migrations.AddIndex(
            model_name='amistad',
            index=models.Index(fields=['estado'], name='social_amis_estado_1e1e38_idx'),
        ),
        migrations.AddConstraint(
            model_name='amistad',
            constraint=models.UniqueConstraint(fields=('user', 'user2'), name='unique_solicitud_amistad_direccion'),
        ),
    ]
