# Generated by Django 5.0.3 on 2026-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fechaEstreno', models.DateField()),
                ('fechaFin', models.DateField(null=True)),
                ('imagenPortada', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroEpisodios', models.IntegerField()),
                ('valoracionMedia', models.FloatField()),
                ('totalValoraciones', models.IntegerField()),
                ('estado', models.CharField(max_length=255)),
                ('generos', models.ManyToManyField(to='serie.genero')),
            ],
        ),
    ]
